# Generated by Django 4.2.6 on 2023-11-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_manthanouser_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(default='default-pb.png', upload_to='profile_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default-pp.png', upload_to='profile_images/'),
        ),
    ]
