# Generated by Django 4.2.6 on 2024-08-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroom_professor_managed'),
        ('authentication', '0003_subject_manthanouser_academic_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manthanouser',
            name='academic_email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manthanouser',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='classroom.classroom'),
        ),
    ]
