# Generated by Django 4.2.6 on 2023-11-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_profile_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(null=True, upload_to='profile_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
