# Generated by Django 4.2.6 on 2023-10-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_code_alter_classroom_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
